		var hmprod = ["img/men-product/hmprod (1).jpg","img/men-product/hmprod (2).jpg","img/men-product/hmprod (4).jpg","img/men-product/hmprod (6).jpg","img/men-product/hmprod (8).jpg","img/men-product/hmprod (10).jpg"];
		var hmprodimg = ["img/men-product/hmprod.jpg","img/men-product/hmprod (3).jpg","img/men-product/hmprod (5).jpg","img/men-product/hmprod (7).jpg","img/men-product/hmprod (9).jpg","img/men-product/hmprod (11).jpg"];
			$('#hmprod1').hover(function(){
				$('#hmprod1-img').attr("src",hmprodimg[0]);
			},
			function(){
				$('#hmprod1-img').attr("src",hmprod[0]);
				}
			);
			$('#hmprod2').hover(function(){
				$('#hmprod2-img').attr("src",hmprodimg[1]);
			},
			function(){
				$('#hmprod2-img').attr("src",hmprod[1]);
				}
			);
			$('#hmprod3').hover(function(){
				$('#hmprod3-img').attr("src",hmprodimg[2]);
			},
			function(){
				$('#hmprod3-img').attr("src",hmprod[2]);
				}
			);
			$('#hmprod4').hover(function(){
				$('#hmprod4-img').attr("src",hmprodimg[3]);
			},
			function(){
				$('#hmprod4-img').attr("src",hmprod[3]);
				}
			);
			$('#hmprod5').hover(function(){
				$('#hmprod5-img').attr("src",hmprodimg[4]);
			},
			function(){
				$('#hmprod5-img').attr("src",hmprod[4]);
				}
			);
			$('#hmprod6').hover(function(){
				$('#hmprod6-img').attr("src",hmprodimg[5]);
			},
			function(){
				$('#hmprod6-img').attr("src",hmprod[5]);
				}
			);
